### ISSUE TITLE
Theme demo broken after latest updates

### ISSUE THREAD

**Issue by onedrawingperday** [ThemeTony/hugo-theme-tony#1]
Hello again @FFRaycoder 

The latest updates broke the theme demo on the Hugo Showcase.

[Line 200](https://github.com/ThemeTony/hugo-theme-tony/blob/master/exampleSite/config.toml#L200) of `exampleSite/config.toml` contains a syntax error that is causing the demo to break.

Furthermore I did notice that you reverted [lines 7-9](https://github.com/ThemeTony/hugo-theme-tony/blob/master/exampleSite/config.toml#L7-L9) so that the default language of the demo is again set to Mandarin.

As [I have already said when you submitted the theme](https://github.com/gohugoio/hugoThemes/issues/841#issuecomment-626349013) the default language of the demo config needs to be set to English since the content on the Hugo Themes website meant for an international audience.

I kindly request that **in the future please refrain from reverting changes that were requested during the submission process of your theme**.

Hugo themes deployment is monitored and sooner or later I will find out about changes that affect the user experience of Hugo Themes visitors.

Once you do the above changes please let me know.

cc: @digitalcraftsman

**Comment by FFRaycoder** [comment]
Hi.
It was my fault, I simply translated `config.toml`: smirk:
Already fixed in [4ce7c20
](https://github.com/ThemeTony/hugo-theme-tony/commit/4ce7c20fe60a98ae27d1846fe09cdfa23b18958d)

**Comment by onedrawingperday** [comment]
Ok thank you for the swift reply.

There is a typo and I left a comment in 4ce7c20

I will update the theme later today to fix the the demo.

**Comment by FFRaycoder** [comment]
ok.
