### ISSUE TITLE
Theme still broken

### ISSUE THREAD

**Issue by onedrawingperday** [ThemeTony/hugo-theme-tony#2]
@FFRaycoder 

Apparently now there is another ERROR:

```
3:46:34 PM: Error: from config: error decoding '': media type "application / rss + xml" not found
```
The mediatype should not have spaces.
`    mediaType = "application/rss+xml"`

Fix this in every output format definition in both of the theme's configs.

Then you need to regenerate and commit the theme's resources because they are not up to date.

Once you do the above let me know, so that I can see if the theme demo generates.

**Comment by FFRaycoder** [comment]
i will fix that later.i’m not home now👀

**Comment by FFRaycoder** [comment]
fixed in [here](https://github.com/ThemeTony/hugo-theme-tony/commit/9f7dba49abd1875c27c3cd24798ae87711d8227c)

**Comment by onedrawingperday** [comment]
You also need to **regenerate and commit the theme’s resources** as stated in the [Hugo Themes repi guidelines](https://github.com/gohugoio/hugoThemes/blob/master/README.md#resources)

**Comment by FFRaycoder** [comment]
see: <https://github.com/ThemeTony/hugo-theme-tony/commit/ccfd805540a610a081704d5bc8b58117bafba237>

**Comment by onedrawingperday** [comment]
Updated in https://github.com/gohugoio/hugoThemes/commit/929e2b5e26cb36625713771d426efe8cd06a719e
