### ISSUE TITLE
Configure date format

### ISSUE THREAD

**Issue by justjosias** [ThemeTony/hugo-theme-tony#5]
I don't know if Hugo supports this by default or not, but I would like to use the date format `2020-05-24` rather than `24-05-20`.

**Comment by justjosias** [comment]
https://gohugo.io/functions/dateformat/

**Comment by FFRaycoder** [comment]
hi, see ouorz.com
I’m just porting:trollface:

**Comment by FFRaycoder** [comment]
And thank you for using my theme!!!!!!!

**Comment by FFRaycoder** [comment]
Maybe you want to customize, I will consider adding a configuration
